server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456789
    url: jdbc:postgresql://localhost:5432/YemekTarifiUygulamaAuthDB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}
