server:
  port: 9093

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: YemekTarifiUygulamaDB
      username: JavaUser
      password: root

jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}