server:
  port: 9095

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root

  mail:
    username: ${USERNAME}
    # Google account manager'daki uygulama şifrelerden oluşturuldu.
    password: ${PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
rabbitmq:
  registerMailQueue: mail-queue
  favoriteCategoryQueue: favoriteCategoryQueue
