server:
  port: 9091

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: YemekTarifiKitabiUserProfileDB
      username: JavaUser
      password: root

jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}
